short-read-mngs RunAssembly: contig length filter
chanzuckerberg/idseq-workflows pull request #127
Opened 2021-06-03 22:53 UTC by mlin

Apply a 100-nucleotide length filter to the contigs as they emerge from SPAdes, to reduce the burden on subsequent steps like BlastContigs. Shorter contigs can make up a majority of SPAdes output currently (sample-dependent), yet seem of minimal value considering they're shorter than the input reads.

The downfiltered contigs are used for all subsequent steps (including the Bowtie2 realignment of reads to contigs immediately following SPAdes). The original set is copied into a new workflow output, `assembly_out_assembly_contigs_all_fasta`, which remains unused.

2021-06-04 15:57 UTC, katrinakalantar reviewed
This looks good to me, I added a few minor comments. 
I'll let @morsecodist give the final approval.

2021-06-04 15:57 UTC, katrinakalantar commented on short-read-mngs/postprocess.wdl
> +    File assembly_out_assembly_contigs_all_fasta = RunAssembly.assembly_contigs_all_fasta
Great that we're still outputting the full assembled contig file!

2021-06-04 15:57 UTC, katrinakalantar commented on short-read-mngs/test/README.md
> +DOCKER_IMAGE_ID=idseq-short-read-mngs make test-short-read-mngs
Should these be a single line?

2021-06-04 15:57 UTC, katrinakalantar commented on short-read-mngs/idseq-dag/idseq_dag/util/fasta.py
> +                    yield Read(header, ("".join(sequence_wip) if len(sequence_wip) != 1 else sequence_wip[0]))
Is there a particular reason to include the `if len(sequence_wip) != 1` statement? I think the same result would be achieved if `"".join(sequence_wip)` was used even for cases where `sequence_wip` only has length = 1, but am not certain of if this was done for efficiency purposes.

2021-06-04 15:57 UTC, katrinakalantar commented on short-read-mngs/test/postprocess/test_RunAssembly.py
> +    assert contigs_headers and (set(contigs_all_headers) - set(contigs_headers))
optional: for completeness, should we additionally assert on the length of a sequence in `set(contigs_all_headers) - set(contigs_headers)` to ensure length is < `min_contig_length`?

2021-06-04 16:27 UTC, morsecodist requested changes
Looks great overall. Love the tests. Just a few small tweaks.

2021-06-04 16:27 UTC, morsecodist commented on short-read-mngs/idseq-dag/idseq_dag/steps/run_assembly.py
> +                    for record in fasta.iterator(assembled_contig_all):
I am trying to move us away from custom parsing. We already have bio python as a dependency. Could you replace with something like:

```python
from Bio import SeqIO

SeqIO.write(
    (r for r in SeqIO.parse(assembled_contig_all, "fasta") if len(r.seq) >= min_contig_length),
    assembled_contig,
    "fasta",
)
```

This would make your changes in short-read-mngs/idseq-dag/idseq_dag/util/fasta.py unnecessary

2021-06-04 16:27 UTC, morsecodist commented on short-read-mngs/idseq-dag/idseq_dag/util/fasta.py
>  def iterator(fasta_file: str) -> Iterator[Read]:
As mentioned in my other comment these changes might be unnecessary

2021-06-04 16:27 UTC, morsecodist commented on short-read-mngs/postprocess.wdl
> +    Int min_contig_length
Can you set the default here and make it optional so it is more obvious and we could disable it more cleanly if we ever support that?

```
Int? min_contig_length = 100
```

Assuming we can explicitly pass in null here.

2021-06-04 16:27 UTC, morsecodist commented on short-read-mngs/idseq-dag/idseq_dag/steps/run_assembly.py
> +        min_contig_length = int(self.additional_attributes.get('min_contig_length', 0))
See comment about moving the default. Also here it looks like the default is no filtering rather than 100?

2021-06-05 22:14 UTC, mlin commented on short-read-mngs/postprocess.wdl
> +    Int min_contig_length
I'm setting the default at the workflow-level input rn: https://github.com/chanzuckerberg/idseq-workflows/pull/127/files#diff-d2e6572472ef03a6e96e659a5de68aaf3c3954db41875231be060bbaf4e3a8c0R484

There's actually an ambiguity in the WDL spec we're [working to clarify right now](https://github.com/openwdl/wdl/pull/464) that makes it awkward to set the default value inside the task, but also expose a workflow-level input to optionally override it. It's funny it comes up organically here, as we were just having a healthy debate about that PR last week.

If we needed to, we'd set the workflow-level input to 0.

2021-06-05 22:16 UTC, mlin commented on short-read-mngs/test/README.md
> +DOCKER_IMAGE_ID=idseq-short-read-mngs make test-short-read-mngs
That just makes the definition effective only for this invocation instead of the rest of the shell session (since `DOCKER_IMAGE_ID` is a pretty generic name)

2021-06-05 22:18 UTC, mlin commented on short-read-mngs/idseq-dag/idseq_dag/steps/run_assembly.py
> +                    for record in fasta.iterator(assembled_contig_all):
Agreed and implemented. I found I had to add biopython to the idseq-dag setup.py requires, I guess the production Dockerfile installs it separately.

2021-06-05 22:28 UTC, mlin commented on short-read-mngs/idseq-dag/idseq_dag/util/fasta.py
> +                    yield Read(header, ("".join(sequence_wip) if len(sequence_wip) != 1 else sequence_wip[0]))
(obviated)

2021-06-09 15:32 UTC, morsecodist approved these changes
Looks good thanks!

2021-06-09 20:46 UTC, merged