Update Consensus Genomes workflow to handle Oxford Nanopore data
chanzuckerberg/idseq-workflows pull request #86
Opened 2021-03-06 23:47 UTC by kislyuk

This builds on @katrinakalantar's prototyping branch, https://github.com/chanzuckerberg/idseq-workflows/tree/kkalantar-prototype-ont-cg.

2021-03-08 18:37 UTC, kislyuk commented
The diff of the WDL from @katrinakalantar's original prototype can be seen at https://github.com/chanzuckerberg/idseq-workflows/compare/kkalantar-prototype-ont-cg..akislyuk-cg-updates (scroll to `consensus-genome/run.wdl`, click "Load diff").

2021-03-08 20:36 UTC, kislyuk commented
Notes from sync with @katrinakalantar:
* `primer_schemes/nCoV-2019.reference.fasta` must be used as reference fasta when in ONT mode for consistency with ARTIC internal tooling.
* Quast input fastqs correct value is fastqs = RemoveHost.host_removed_fastqs.
* Unclear why `flatten()` is being used, check if Tiago knows
* Let's add an input check in the WDL itself or in the validate task to make sure only 1 fastq is passed in ONT mode
* In RemoveHost, let's simplify the InsufficientReads conditional to just look at whether the first filtered fastq is empty
* In RunMinion, need to check if we are emitting the correct sorted bam files
* Need to decide whether it's OK to run `artic minion --no-longshot`
* FIXME: make explicit conditional on technology not on # of fastqs (@kislyuk)
* In computeStats, remove `depths = np.array([0]*pysam.AlignmentFile("~{cleaned_bam}", "rb").lengths[0])` - this branch is only reached on empty input, which should have thrown an error earlier

2021-03-08 23:48 UTC, katrinakalantar requested changes
These are a bunch of comments - please let me know if I can add any additional context / answer questions on these. Some comments include requested changes. 

One outstanding big-picture question (also mentioned in a comment) is around how we want to handle the logic to selectively run VADR for sars-cov-2 given that this workflow will also be used for generic-CG.

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/run.wdl
> +        samtools sort "~{sample}.trimmed.rg.sorted.bam" > "~{sample}.trimmed.rg.resorted.bam"
I apologize for the mis-identified file here in the prototype wdl. This should actually be modified to use the primertrimmed .bam file since this is what is used within `artic minion` for consensus calling.
 
```
samtools sort "~{sample}.primertrimmed.rg.sorted.bam" > "~{sample}.primertrimmed.rg.resorted.bam"
mv "~{sample}.primertrimmed.rg.resorted.bam" "~{sample}.primertrimmed.rg.sorted.bam"
samtools index "~{sample}.primertrimmed.rg.sorted.bam" # to create "~{sample}.primertrimmed.rg.sorted.bai"
```

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/run.wdl
> +        File alignedbam = "~{sample}.trimmed.rg.sorted.bam"
Similar to above, this is my bad. We want to provide the raw alignment result here to be comparable to the Illumina workflow. 

This should be:
`File alignedbam = "~{sample}.sorted.bam"`

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/run.wdl
> +            depths = np.array([0]*pysam.AlignmentFile("~{cleaned_bam}", "rb").lengths[0])
Per our discussion earlier today, we should be fine to remove this line (should throw some sort of informative error if we get to the point that there are no depth results -> as a result of no coverage).

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/run.wdl
> +    call Vadr {
I'm not sure if this belongs in this code review, but wanted to highlight that since this .wdl will also be used to also support the generic CG workflow for Illumina data, we will need to make sure that this call is somehow conditional on the reference genome or another proxy for "organism" to limit to sars-cov-2.

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/run.wdl
> +        artic minion --medaka --no-longshot --normalise "~{normalise}" --threads 4 --scheme-directory primer_schemes --read-file ~{sep=' ' fastqs} --medaka-model "~{medaka_model}" nCoV-2019/V3 "~{sam
using the `--no-longshot` parameter should be suitable, we will thus rely on the medaka variants (see this feature deployed in artic [v1.2.0](https://github.com/artic-network/fieldbioinformatics/releases/tag/1.2.0)).

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/test/test_wdl.py
> +    def test_illumina_cg(self):
this is so great to have this validation in place! also really helpful to see how the structure can be used for validation of pipeline output metrics.

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/run.wdl
> +        File vcf = "~{sample}.merged.vcf"
Here, I think we should still be using the above line:
`File vcf_pass = "~{sample}.merged.pass.vcf"` 
...since the full .vcf contains all potential variants (including very low-quality variants). This leads to inflation of the `n_snps` number in the output stats.json file. Reporting only high-quality variants will also keep parity with the Illumina outputs.

2021-03-08 23:48 UTC, katrinakalantar commented on consensus-genome/test/test_wdl.py
> +        self.assertEqual(output_stats["ref_snps"], 77)
This tipped me off to the fact that we should be replacing `*.merged.vcf` to `*.merged.pass.vcf` in the `RunMinion` step. The number of SNPs should drop substantially after that change.

2021-03-11 19:45 UTC, kislyuk commented on consensus-genome/run.wdl
> +                fastqs_1 = fastqs_1,
Fixed by removing fastqs_1 from the ApplyLengthFilter input signature and call.

2021-03-12 20:23 UTC, kislyuk commented on consensus-genome/run.wdl
> +    command <<<
I think we should keep this task as a placeholder and I absolutely agree we need that logic in here. I'll try to add it myself but may have to offload that task to someone else given the urgency of shipping v0.

2021-03-12 20:23 UTC, kislyuk commented on consensus-genome/run.wdl
> +    # At this point, the output filenames from the ONT pipeline have diverged from the outut filenames
Removed as discussed.

2021-03-12 21:01 UTC, kislyuk commented on consensus-genome/run.wdl
> +        samtools sort "~{sample}.trimmed.rg.sorted.bam" > "~{sample}.trimmed.rg.resorted.bam"
Thanks, updated.

2021-03-12 21:02 UTC, kislyuk commented on consensus-genome/run.wdl
> +        File alignedbam = "~{sample}.trimmed.rg.sorted.bam"
Updated this one as well.

2021-03-12 21:03 UTC, kislyuk commented on consensus-genome/run.wdl
> +        File vcf = "~{sample}.merged.vcf"
Ah, but that file does not exist (I believe this changed after adding `--no-longshot`). Can you take a look at the listing in the RunMinion log I shared and see if there is an acceptable substitute?
```
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE + ls
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE _miniwdl_inputs
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE primer_schemes
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.alignreport.er
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.alignreport.txt
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.consensus.fasta
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.coverage_mask.txt
2021-03-08 20:03:17.163 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.coverage_mask.txt.nCoV-2019_1.depths
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.coverage_mask.txt.nCoV-2019_2.depths
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.fail.vcf
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.merged.vcf
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.minion.log.txt
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.muscle.in.fasta
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.muscle.out.fasta
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.nCoV-2019_1.hdf
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.nCoV-2019_1.vcf
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.nCoV-2019_2.hdf
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.nCoV-2019_2.vcf
2021-03-08 20:03:17.164 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.pass.vcf.gz
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.pass.vcf.gz.tbi
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.preconsensus.fasta
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.primers.vcf
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.primersitereport.txt
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.primertrimmed.rg.sorted.bam
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.primertrimmed.rg.sorted.bam.bai
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.sorted.bam
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.sorted.bam.bai
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.trimmed.rg.sorted.bam
2021-03-08 20:03:17.165 wdl.w:consensus_genome.t:call-RunMinion.stderr VERBOSE test_sample.trimmed.rg.sorted.bam.bai
```

2021-03-12 23:32 UTC, kislyuk commented on consensus-genome/run.wdl
> +    call Vadr {
Added a `TODO` here to ensure we don't forget, but I won't be adding the conditional since the input signature for Generalized CG is not defined in this PR.

2021-03-12 23:34 UTC, kislyuk commented on consensus-genome/run.wdl
> +            depths = np.array([0]*pysam.AlignmentFile("~{cleaned_bam}", "rb").lengths[0])
Replaced this line with `raise Exception("Insufficient coverage to proceed with CG analysis")`.

2021-03-16 19:38 UTC, katrinakalantar reviewed
These changes look like they address all of the items discussed above!

2021-03-16 19:43 UTC, katrinakalantar commented
One thing to call out explicitly is that this branch will break idseq-workflows for general viral consensus genomes until a subsequent change is made to make the VADR step conditional on reference_genome == sars-cov-2.

2021-03-16 19:44 UTC, katrinakalantar approved these changes

2021-03-16 19:45 UTC, kislyuk commented
Thanks, yes, I left a comment to that effect. I will be implementing the relevant logic for general CG, so I'll take care of that change.

2021-03-16 21:01 UTC, merged